### ISSUE TITLE
Discord integration issue

### ISSUE THREAD

**Issue by paz** [AnvilPowered/Catalyst#49]
```
[09:51:54 INFO] [catalyst]: xPaz has joined the proxy
[09:51:54 ERROR]: Oct 29, 2020 9:51:54 AM com.google.common.eventbus.EventBus$LoggingHandler handleException
[09:51:54 ERROR]: SEVERE: Exception thrown by subscriber method onPlayerJoinEvent(org.anvilpowered.catalyst.api.event.JoinEvent) on subscriber org.anvilpowered.catalyst.common.listener.CommonDiscordChatListener@2c806135 when dispatching event: org.anvilpowered.catalyst.common.event.CommonJoinEvent@15b6b633
[09:51:54 ERROR]: java.lang.NullPointerException
[09:51:54 ERROR]: at org.anvilpowered.catalyst.common.discord.CommonWebhookSender.getWebhook(CommonWebhookSender.java:81)
[09:51:54 ERROR]: at org.anvilpowered.catalyst.common.discord.CommonWebhookSender.sendWebhookMessage(CommonWebhookSender.java:49)
[09:51:54 ERROR]: at org.anvilpowered.catalyst.common.listener.CommonDiscordChatListener.onPlayerJoinEvent(CommonDiscordChatListener.java:156)
[09:51:54 ERROR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:51:54 ERROR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:51:54 ERROR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:51:54 ERROR]: at java.lang.reflect.Method.invoke(Method.java:498)
[09:51:54 ERROR]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
[09:51:54 ERROR]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
[09:51:54 ERROR]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
[09:51:54 ERROR]: at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
[09:51:54 ERROR]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
[09:51:54 ERROR]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
[09:51:54 ERROR]: at com.google.common.eventbus.EventBus.post(EventBus.java:212)
[09:51:54 ERROR]: at org.anvilpowered.catalyst.velocity.listener.VelocityListener.lambda$null$1(VelocityListener.java:139)
[09:51:54 ERROR]: at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
[09:51:54 ERROR]: at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
[09:51:54 ERROR]: at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
[09:51:54 ERROR]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[09:51:54 ERROR]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[09:51:54 ERROR]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[09:51:54 ERROR]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
[09:51:54 ERROR]:
```

```

```

**Desktop (please complete the following information):**
 - Velocity Version: Velocity 1.1.2-SNAPSHOT (git-f3e1a7e0-b294)
 - Catalyst Version: 08b6885 / build #60 on CI, also happens on 0.2.1 (both using matching anvil versions)
 - Additional Plugins installed on velocity: anvil, bungeequack, luckperms, catalyst, craftingstore, joinkick, minimotd-velocity, pingcommand, plan, velocityguard

**Comment by paz** [comment]
Staff chat works as expected, but not global/main chat

**Comment by paz** [comment]
Issue resolved by making the channel name shorter, maybe theres a limit
